---
- name: Hello World Sample
  hosts: all
  
  vars:
    editeur: "{{ EDITEUR|default('oracle') }}"
    version: "{{ VERSION|default('8') }}" 
    subversion: "{{ SUBVERSION|default('151') }}"
  
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    
    - name: Check var
      debug:
        msg: "The ansible slave is {{ pacman }}"
     
    - name: Check array
      debug: msg={{item}}
      with_items: "{{ ghosts }}"
      
    - name: check jdk
      debug: msg="jdk {editeur version subversion}"
