---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    
    - name: Check var
      debug:
      msg: "The ansible slave is {{ pacman }}"
     
    - name: Check array
      debug: var={{item}}
      with_items: "{{ ghosts }}"
