- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - debug:
      msg: "The ansible slave is {{ pacman }}"
     
    - debug: var={{item}}
      with_items: ghosts
